# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту mailto:vichukano@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - vichukano@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

before_install:
  - export TZ=Europe/Moscow
  - psql -c "CREATE DATABASE cinema;" -U postgres
  - psql -c "CREATE DATABASE test_cinema;" -U postgres
  - psql -c "CREATE DATABASE carprice;" -U postgres
  - psql -c "CREATE DATABASE carprice_test;" -U postgres
  - psql -c "CREATE DATABASE test_carprice;" -U postgres
services:
  - postgresql
addons:
      postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE tracker;" -U postgres
  - psql -c "CREATE DATABASE parser_testing;" -U postgres
  - psql -c "CREATE DATABASE servlet_test;" -U postgres
  - psql -c "CREATE DATABASE todolist_test;" -U postgres
  - psql -c "CREATE DATABASE carstorage;" -U postgres
